# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Projects
    url: /#projects
    weight: 20
  - name: Contact
    url: /#contact
    weight: 30
  - name: CV
    url: /#cv
    weight: 40
  # - name: About
  #   weight: 40
  #   hasChildren: true
  # - parent: About
  #   name: CV
  #   url: Laureijs-CV.pdf
  # - parent: About
  #   name: News
  #   url: blog/
  # - name: Blog
  #   url: /blog/
  #   weight: 40
